### ISSUE TITLE
Is this still automatically built? 

### ISSUE THREAD

**Issue by ejsuncy** [Motion-Project/motion-docker#11]
The last update to this image was 8 months ago, but code has been pushed to Motion-Project/motion:master more recently

**Comment by Mr-DaveDev** [comment]
I think that this is now dead due to the changes in Travis/Docker.

**Comment by hannesa2** [comment]
Any chance to repair this ?

**Comment by hannesa2** [comment]
I see you removed it complete https://github.com/Motion-Project/motion/commit/82de1e15d55dc733de750330f7b9e67688ac9bf1 but where is the part for upload. Please can you point me to it ?

Is a move to github action an option ? I at least do [this upload with actions](https://github.com/hannesa2/dockerAndroidNDK/blob/master/.github/workflows/docker-image.yml)

**Comment by tuxthepenguin84** [comment]
Hi I've forked this project to get it up to date with Ubuntu 20.04 and the latest motion release. I have two tags so far, one is just based on the .deb file (all features) another is built from source, uses Alpine Linux, and removes some functionality I do not use to significantly reduce footprint of the container (~82MB):

https://github.com/tuxthepenguin84/motion-docker
https://hub.docker.com/r/tuxthepenguin/motion

It's very much a work in progress but wanted to let the community know.
