### ISSUE TITLE
Motion on docker hub

### ISSUE THREAD

**Issue by jwater7** [Motion-Project/motion-docker#3]
The motion project really needs an official Docker image (such as motion/motion:latest).  I’ve been running it successfully in one for a while now, but I think it would be prudent to start that conversation and maybe start releasing them after each release cycle as a supported platform (which may at some point imply design considerations for the future of the project).

I have a very bare-bones example at https://hub.docker.com/r/jwater7/motion/ (https://github.com/jwater7/docker-motion) if you’d like to take a look.  I would suggest installing from source and using an alpine base for the official one though.

**Comment by deece** [comment]
The motioneye frontend for motion has a docker image, which contains the latest release. Does that meet your needs? https://github.com/ccrisan/motioneye/wiki/Install-In-Docker

**Comment by steveneighbour** [comment]
That's not a worry.   Next time you want to force a build, just push something to the readme.md in the docker repo (eg update the version number).  This will trigger a build for people to use if they wish.

I've a second lot of edits to merge, so will include an eg of what i mean.
