### ISSUE TITLE
Adding MQTT

### ISSUE THREAD

**Issue by lolouk44** [Motion-Project/motion-docker#9]
More of a new feature request than an issue
I use the docker image and I post a message to MQTT when an even is detected:
```
on_event_start mosquitto_pub -h 192.168.0.24 -p 1883 -u xx -P yyy -t Sensors/CCTV2/Doorbell/Motion -q 1 -m ON -r
on_event_end mosquitto_pub -h 192.168.0.24 -p 1883 -u xx -P yyy -t Sensors/CCTV2/Doorbell/Motion -q 1 -m OFF -r
```
MQTT is not included with motion by default.
could it be added for interoperability with other systems?
If not is there a way to install MQTT first and then run motion without having to manually build my own dockerfile?

**Comment by tosiara** [comment]
The correct way to add custom packages would be to build a local image.
Like this: https://stackoverflow.com/questions/45181713/how-can-i-add-software-or-other-packages-to-a-docker-container
